// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePerson = "people"

// Person mapped from table <people>
type Person struct {
	Name string `gorm:"column:name" json:"name"`
}

// TableName Person's table name
func (*Person) TableName() string {
	return TableNamePerson
}
