// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"entities-module/model"
)

func newAddress(db *gorm.DB, opts ...gen.DOOption) address {
	_address := address{}

	_address.addressDo.UseDB(db, opts...)
	_address.addressDo.UseModel(&model.Address{})

	tableName := _address.addressDo.TableName()
	_address.ALL = field.NewAsterisk(tableName)
	_address.AddressID = field.NewInt32(tableName, "address_id")
	_address.Address = field.NewString(tableName, "address")
	_address.Address2 = field.NewString(tableName, "address2")
	_address.District = field.NewString(tableName, "district")
	_address.CityID = field.NewInt16(tableName, "city_id")
	_address.PostalCode = field.NewString(tableName, "postal_code")
	_address.Phone = field.NewString(tableName, "phone")
	_address.LastUpdate = field.NewTime(tableName, "last_update")

	_address.fillFieldMap()

	return _address
}

type address struct {
	addressDo

	ALL        field.Asterisk
	AddressID  field.Int32
	Address    field.String
	Address2   field.String
	District   field.String
	CityID     field.Int16
	PostalCode field.String
	Phone      field.String
	LastUpdate field.Time

	fieldMap map[string]field.Expr
}

func (a address) Table(newTableName string) *address {
	a.addressDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a address) As(alias string) *address {
	a.addressDo.DO = *(a.addressDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *address) updateTableName(table string) *address {
	a.ALL = field.NewAsterisk(table)
	a.AddressID = field.NewInt32(table, "address_id")
	a.Address = field.NewString(table, "address")
	a.Address2 = field.NewString(table, "address2")
	a.District = field.NewString(table, "district")
	a.CityID = field.NewInt16(table, "city_id")
	a.PostalCode = field.NewString(table, "postal_code")
	a.Phone = field.NewString(table, "phone")
	a.LastUpdate = field.NewTime(table, "last_update")

	a.fillFieldMap()

	return a
}

func (a *address) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *address) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 8)
	a.fieldMap["address_id"] = a.AddressID
	a.fieldMap["address"] = a.Address
	a.fieldMap["address2"] = a.Address2
	a.fieldMap["district"] = a.District
	a.fieldMap["city_id"] = a.CityID
	a.fieldMap["postal_code"] = a.PostalCode
	a.fieldMap["phone"] = a.Phone
	a.fieldMap["last_update"] = a.LastUpdate
}

func (a address) clone(db *gorm.DB) address {
	a.addressDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a address) replaceDB(db *gorm.DB) address {
	a.addressDo.ReplaceDB(db)
	return a
}

type addressDo struct{ gen.DO }

type IAddressDo interface {
	gen.SubQuery
	Debug() IAddressDo
	WithContext(ctx context.Context) IAddressDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAddressDo
	WriteDB() IAddressDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAddressDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAddressDo
	Not(conds ...gen.Condition) IAddressDo
	Or(conds ...gen.Condition) IAddressDo
	Select(conds ...field.Expr) IAddressDo
	Where(conds ...gen.Condition) IAddressDo
	Order(conds ...field.Expr) IAddressDo
	Distinct(cols ...field.Expr) IAddressDo
	Omit(cols ...field.Expr) IAddressDo
	Join(table schema.Tabler, on ...field.Expr) IAddressDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAddressDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAddressDo
	Group(cols ...field.Expr) IAddressDo
	Having(conds ...gen.Condition) IAddressDo
	Limit(limit int) IAddressDo
	Offset(offset int) IAddressDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAddressDo
	Unscoped() IAddressDo
	Create(values ...*model.Address) error
	CreateInBatches(values []*model.Address, batchSize int) error
	Save(values ...*model.Address) error
	First() (*model.Address, error)
	Take() (*model.Address, error)
	Last() (*model.Address, error)
	Find() ([]*model.Address, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Address, err error)
	FindInBatches(result *[]*model.Address, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Address) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAddressDo
	Assign(attrs ...field.AssignExpr) IAddressDo
	Joins(fields ...field.RelationField) IAddressDo
	Preload(fields ...field.RelationField) IAddressDo
	FirstOrInit() (*model.Address, error)
	FirstOrCreate() (*model.Address, error)
	FindByPage(offset int, limit int) (result []*model.Address, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAddressDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a addressDo) Debug() IAddressDo {
	return a.withDO(a.DO.Debug())
}

func (a addressDo) WithContext(ctx context.Context) IAddressDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a addressDo) ReadDB() IAddressDo {
	return a.Clauses(dbresolver.Read)
}

func (a addressDo) WriteDB() IAddressDo {
	return a.Clauses(dbresolver.Write)
}

func (a addressDo) Session(config *gorm.Session) IAddressDo {
	return a.withDO(a.DO.Session(config))
}

func (a addressDo) Clauses(conds ...clause.Expression) IAddressDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a addressDo) Returning(value interface{}, columns ...string) IAddressDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a addressDo) Not(conds ...gen.Condition) IAddressDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a addressDo) Or(conds ...gen.Condition) IAddressDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a addressDo) Select(conds ...field.Expr) IAddressDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a addressDo) Where(conds ...gen.Condition) IAddressDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a addressDo) Order(conds ...field.Expr) IAddressDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a addressDo) Distinct(cols ...field.Expr) IAddressDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a addressDo) Omit(cols ...field.Expr) IAddressDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a addressDo) Join(table schema.Tabler, on ...field.Expr) IAddressDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a addressDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAddressDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a addressDo) RightJoin(table schema.Tabler, on ...field.Expr) IAddressDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a addressDo) Group(cols ...field.Expr) IAddressDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a addressDo) Having(conds ...gen.Condition) IAddressDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a addressDo) Limit(limit int) IAddressDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a addressDo) Offset(offset int) IAddressDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a addressDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAddressDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a addressDo) Unscoped() IAddressDo {
	return a.withDO(a.DO.Unscoped())
}

func (a addressDo) Create(values ...*model.Address) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a addressDo) CreateInBatches(values []*model.Address, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a addressDo) Save(values ...*model.Address) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a addressDo) First() (*model.Address, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Address), nil
	}
}

func (a addressDo) Take() (*model.Address, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Address), nil
	}
}

func (a addressDo) Last() (*model.Address, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Address), nil
	}
}

func (a addressDo) Find() ([]*model.Address, error) {
	result, err := a.DO.Find()
	return result.([]*model.Address), err
}

func (a addressDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Address, err error) {
	buf := make([]*model.Address, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a addressDo) FindInBatches(result *[]*model.Address, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a addressDo) Attrs(attrs ...field.AssignExpr) IAddressDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a addressDo) Assign(attrs ...field.AssignExpr) IAddressDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a addressDo) Joins(fields ...field.RelationField) IAddressDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a addressDo) Preload(fields ...field.RelationField) IAddressDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a addressDo) FirstOrInit() (*model.Address, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Address), nil
	}
}

func (a addressDo) FirstOrCreate() (*model.Address, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Address), nil
	}
}

func (a addressDo) FindByPage(offset int, limit int) (result []*model.Address, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a addressDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a addressDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a addressDo) Delete(models ...*model.Address) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *addressDo) withDO(do gen.Dao) *addressDo {
	a.DO = *do.(*gen.DO)
	return a
}
